# Generated by Django 2.2.4 on 2019-08-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('pingUrl', models.TextField()),
                ('interval', models.IntegerField()),
                ('waitTime', models.IntegerField()),
            ],
        ),
    ]
