# Generated by Django 2.2.4 on 2019-08-09 08:32

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specs',
            name='id',
        ),
        migrations.AddField(
            model_name='specs',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specs',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
